### ISSUE TITLE
training results are flat

### ISSUE THREAD

**Issue by gburachas** [junhyukoh/caffe-lstm#7]
HI, 
I ran ./test_lstm_long.sh and other scripts on an Ubuntu box, and the result in the log file is flat:
...
-0.138143 0.087998
-0.118875 0.087998
-0.0895481 0.087998
-0.0522323 0.087998
-0.00979323 0.087998
...

Any suggestions?
Also, by default the mode is CPU, and the scripts crash when the flag in *solver.prototxt is changed to GPU. I use C2070, which works fine with other caffe projects.

thanks-
GTB

**Comment by junhyukoh** [comment]
Hi,
- There was a bug in LSTM when "clip" is set to 1 for the first time-step. I fixed it now.
- I changed my code and prototxts to support GPU mode in examples.
  However, it will be slower than CPU mode because of the data copy overhead from CPU to GPU.
  In general, GPU mode is much faster than CPU mode with large-scale data.

Thank you for reporting this!
